[meta]
project_name = "rainfall-prediction"
timezone = "Asia/Singapore"
created_by = "Rafli"

[versions]
schema = "1.0"

[paths]
data_dir        = "data"
raw_dir         = "data/raw"
interim_dir     = "data/interim"
processed_dir   = "data/processed"
clean_dir       = "data/clean"
inference_dir   = "data/inference"

database_dir    = "app/database"
assets_dir      = "app/assets"
template_dir    = "app/assets/templates"
style_dir       = "app/assets/styles"
models_dir      = "app/models"

metadata_dir    = "metadata"

[api]
host = "0.0.0.0"
port = 8000

[weather]
timezone = "Asia/Singapore"

[features]
rolling_windows = [30, 60, 120]
rain_extreme_columns = [
    'highest_30_min_rainfall_mm',
    'highest_60_min_rainfall_mm',
    'highest_120_min_rainfall_mm'
]
meteorogical_columns = [
    'mean_temperature_c',
    'maximum_temperature_c',
    'minimum_temperature_c',
    'mean_wind_speed_kmh',
    'max_wind_speed_kmh',
]
locations = [
    "Admiralty",
    "Ang Mo Kio",
    "Bukit Panjang",
    "Bukit Timah",
    "Buona Vista",
    "Changi",
    "Choa Chu Kang Central",
    "Choa Chu Kang South",
    "Clementi",
    "East Coast Parkway",
    "Jurong Island",
    "Jurong Pier",
    "Jurong West",
    "Kent Ridge",
    "Kranji Reservoir",
    "Lim Chu Kang",
    "Lower Peirce Reservoir",
    "Macritchie Reservoir",
    "Mandai",
    "Marina Barrage",
    "Marine Parade",
    "Newton",
    "Nicoll Highway",
    "Pasir Panjang",
    "Pasir Ris Central",
    "Pasir Ris West",
    "Paya Lebar",
    "Pulau Ubin",
    "Punggol",
    "Queenstown",
    "Seletar",
    "Sembawang",
    "Sentosa Island",
    "Simei",
    "Somerset Road",
    "Tai Seng",
    "Tanjong Katong",
    "Tengah",
    "Toa Payoh",
    "Tuas",
    "Tuas South",
    "Ulu Pandan",
    "Upper Peirce Reservoir",
    "Whampoa"
]